apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-entrypoint
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-device-plugin-daemonset
data:
  entrypoint.sh: |-
    #!/bin/bash

    driver_root=""
    container_driver_root=""
    while true; do
      if [[ -f /run/nvidia/validations/host-driver-ready ]]; then
        driver_root=/
        container_driver_root=/host
        if [[ ! -z "$DRIVER_ROOT" ]]; then
          if [[ "${DRIVER_ROOT}" = "${HOST_ROOT}" ]]; then
            driver_root=${DRIVER_ROOT}
          else
            driver_root=${DRIVER_ROOT}
            container_driver_root=/host${DRIVER_ROOT}
            export NVIDIA_CTK_PATH="${DRIVER_ROOT}/toolkit/nvidia-ctk"
          fi
        fi
        break
      elif [[ -f /run/nvidia/validations/driver-ready ]]; then
        driver_root=/run/nvidia/driver
        container_driver_root=$driver_root
        break
      else
        echo "waiting for the driver validations to be ready..."
        sleep 5
      fi
    done

    export NVIDIA_DRIVER_ROOT=$driver_root
    echo "NVIDIA_DRIVER_ROOT=$NVIDIA_DRIVER_ROOT"

    export CONTAINER_DRIVER_ROOT=$container_driver_root
    echo "CONTAINER_DRIVER_ROOT=$CONTAINER_DRIVER_ROOT"

    echo "NVIDIA_CTK_PATH=$NVIDIA_CTK_PATH"
    echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
    echo "PATH=$PATH"
    echo "Starting nvidia-device-plugin"
    exec nvidia-device-plugin
